Repository Dynatrace/ngx-groundhog, pull requests merged in 2018-02, with the labels that each got.

#38 feat(infrastructure): add publish capabilities
  .travis.yml
  scripts/deploy/publish-build-artifacts.sh
  scripts/travis-deploy.sh
Labels: feature, infrastructure, pr: merge ready

#40 fix(infrastructure): e2e ci gh rate limits
  test/protractor.conf.js
Labels: bug, infrastructure, pr: lgtm

#41 fix(e2e): add gecko false flag to reduce gh requests
  test/protractor.conf.js
  tools/gulp/tasks/e2e.ts
Labels: bug, infrastructure, pr: merge ready

#42 fix(button): variant classes not being added on the server
  src/lib/button/button.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
Labels: bug, pr: lgtm, pr: merge ready

#44 feat(progresscircle): gh-progresscircle
  README.md
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/demo-groundhog-module.ts
  src/demo-app/progress-circle/progress-circle-demo.html
  src/demo-app/progress-circle/progress-circle-demo.scss
  src/demo-app/progress-circle/progress-circle-demo.ts
  src/demo-app/system-config.ts
  src/lib/progress-circle/README.md
  src/lib/progress-circle/index.ts
  src/lib/progress-circle/progress-circle-module.ts
  src/lib/progress-circle/progress-circle.html
  src/lib/progress-circle/progress-circle.scss
  src/lib/progress-circle/progress-circle.spec.ts
  src/lib/progress-circle/progress-circle.ts
  src/lib/progress-circle/public-api.ts
  src/lib/progress-circle/tsconfig-build.json
  src/lib/public-api.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
Labels: feature, new component, pr: lgtm, pr: merge ready

#46 fix(select): animation origin fixed when opening on top
  src/lib/select/select.scss
Labels: bug, pr: lgtm

#54 release(0.0.1)
  package.json
Labels: pr: needs review

#52 feat(ci): add npm publishing capabilities
  scripts/deploy/npm-publish.sh
  scripts/deploy/publish-build-artifacts.sh
Labels: feature, infrastructure, pr: lgtm, pr: merge ready

#56 feat(theming): theming
  package-lock.json
  package.json
  src/demo-app/button/button-demo.html
  src/demo-app/button/button-demo.ts
  src/demo-app/index.html
  src/demo-app/theme.scss
  src/e2e-app/index.html
  src/lib/button/README.md
  src/lib/button/_button-theme.scss
  src/lib/button/button.scss
  src/lib/button/button.spec.ts
  src/lib/button/button.ts
  src/lib/core/_core.scss
  src/lib/core/common-behaviors/color.spec.ts
  src/lib/core/common-behaviors/color.ts
  src/lib/core/common-behaviors/index.ts
  src/lib/core/core.scss
  src/lib/core/style/_interactive-common.scss
  src/lib/core/style/_variables.scss
  src/lib/core/theming/_all-theme.scss
  src/lib/core/theming/_theming.scss
  src/lib/core/theming/prebuilt/_turquoise-theme.scss
  src/lib/core/theming/prebuilt/all.scss
  src/lib/core/theming/prebuilt/turquoise.scss
  src/lib/progress-circle/_progress-circle-theme.scss
  src/lib/progress-circle/progress-circle.scss
  src/lib/select/_select-theme.scss
  src/lib/select/option.scss
  src/lib/select/select.scss
  tools/gulp/gulpfile.ts
  tools/gulp/tasks/release.ts
  tools/package-tools/gulp/build-scss-task.ts
Labels: feature, infrastructure, pr: needs review

#60 fix(select): focus style when disabled
  src/lib/select/select.scss
Labels: bug, pr: lgtm, pr: merge ready

#51 feat(form-field, input): gh-form-field & ghInput
  README.md
  e2e/button-e2e.spec.ts
  e2e/input-e2e.spec.ts
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/demo-groundhog-module.ts
  src/demo-app/input/input-demo.html
  src/demo-app/input/input-demo.scss
  src/demo-app/input/input-demo.ts
  src/demo-app/select/select-demo.html
  src/demo-app/select/select-demo.scss
  src/demo-app/select/select-demo.ts
  src/demo-app/system-config.ts
  src/e2e-app/e2e-app-module.ts
  src/e2e-app/e2e-app/e2e-app.ts
  src/e2e-app/e2e-app/routes.ts
  src/e2e-app/input/input-e2e.html
  src/e2e-app/input/input-e2e.ts
  src/e2e-app/system-config.ts
  src/lib/core/error/error-options.ts
  src/lib/form-field/README.md
  src/lib/form-field/form-field-control.ts
  src/lib/form-field/form-field-errors.ts
  src/lib/form-field/form-field-module.ts
  src/lib/form-field/form-field.html
  src/lib/form-field/form-field.scss
  src/lib/form-field/form-field.ts
  src/lib/form-field/index.ts
  src/lib/form-field/public-api.ts
  src/lib/form-field/tsconfig-build.json
  src/lib/input/README.md
  src/lib/input/index.ts
  src/lib/input/input-module.ts
  src/lib/input/input.scss
  src/lib/input/input.spec.ts
  src/lib/input/input.ts
  src/lib/input/public-api.ts
  src/lib/input/tsconfig-build.json
  src/lib/public-api.ts
  src/lib/select/select.html
  src/lib/select/select.scss
  src/lib/select/select.spec.ts
  src/lib/select/select.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
  test/karma-test-shim.js
Labels: feature, new component, pr: needs review

#61 feat(tile): gh-tile
  README.md
  e2e/tile-e2e.spec.ts
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/demo-groundhog-module.ts
  src/demo-app/system-config.ts
  src/demo-app/tile/tile-demo.html
  src/demo-app/tile/tile-demo.scss
  src/demo-app/tile/tile-demo.ts
  src/e2e-app/e2e-app-module.ts
  src/e2e-app/e2e-app/e2e-app.ts
  src/e2e-app/e2e-app/routes.ts
  src/e2e-app/system-config.ts
  src/e2e-app/tile/tile-e2e.html
  src/e2e-app/tile/tile-e2e.ts
  src/lib/button/_button-theme.scss
  src/lib/button/button.spec.ts
  src/lib/button/button.ts
  src/lib/core/common-behaviors/color.spec.ts
  src/lib/core/common-behaviors/color.ts
  src/lib/core/common-behaviors/index.ts
  src/lib/core/theming/_all-theme.scss
  src/lib/public-api.ts
  src/lib/tile/README.md
  src/lib/tile/_tile-theme.scss
  src/lib/tile/index.ts
  src/lib/tile/public-api.ts
  src/lib/tile/tile-module.ts
  src/lib/tile/tile.html
  src/lib/tile/tile.scss
  src/lib/tile/tile.spec.ts
  src/lib/tile/tile.ts
  src/lib/tile/tsconfig-build.json
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
Labels: feature, new component, pr: lgtm, pr: merge ready

#63 fix(select): width problem on wide selects
  src/lib/select/select.scss
Labels: bug, pr: needs review

#68 feat(island): gh-island
  README.md
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/demo-groundhog-module.ts
  src/demo-app/island/island-demo.html
  src/demo-app/island/island-demo.scss
  src/demo-app/island/island-demo.ts
  src/demo-app/system-config.ts
  src/lib/island/README.md
  src/lib/island/index.ts
  src/lib/island/island-module.ts
  src/lib/island/island.html
  src/lib/island/island.scss
  src/lib/island/island.ts
  src/lib/island/public-api.ts
  src/lib/island/tsconfig-build.json
  src/lib/public-api.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
Labels: feature, new component, pr: lgtm, pr: merge ready

#73 fix(demo-app): fix linting error
  src/demo-app/demo-app/demo-app.scss
Labels: pr: lgtm, pr: merge ready

#72 fix(style): added missing shade of gray
  src/lib/core/style/_variables.scss
Labels: design, pr: lgtm

#70 feat(theming) dark theme, theming directive
  README.md
  src/demo-app/button/button-demo.html
  src/demo-app/demo-app/demo-app.scss
  src/demo-app/demo-groundhog-module.ts
  src/demo-app/index.html
  src/demo-app/system-config.ts
  src/lib/button/_button-theme.scss
  src/lib/core/theming/_theming.scss
  src/lib/core/theming/prebuilt/_turquoise-theme.scss
  src/lib/public-api.ts
  src/lib/theming/README.md
  src/lib/theming/index.ts
  src/lib/theming/public-api.ts
  src/lib/theming/theming-module.ts
  src/lib/theming/theming.spec.ts
  src/lib/theming/theming.ts
  src/lib/theming/tsconfig-build.json
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
Labels: feature, new component, pr: lgtm, pr: merge ready

#45 feat(context-action-menu): gh-context-action-menu
  README.md
  e2e/context-menu-e2e.spec.ts
  src/demo-app/context-menu/context-menu-demo.html
  src/demo-app/context-menu/context-menu-demo.ts
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/demo-groundhog-module.ts
  src/demo-app/system-config.ts
  src/e2e-app/context-menu/context-menu-e2e.html
  src/e2e-app/context-menu/context-menu-e2e.ts
  src/e2e-app/e2e-app-module.ts
  src/e2e-app/e2e-app/e2e-app.ts
  src/e2e-app/e2e-app/routes.ts
  src/e2e-app/system-config.ts
  src/lib/context-menu/README.md
  src/lib/context-menu/context-menu-item.html
  src/lib/context-menu/context-menu-module.ts
  src/lib/context-menu/context-menu.html
  src/lib/context-menu/context-menu.scss
  src/lib/context-menu/context-menu.spec.ts
  src/lib/context-menu/context-menu.ts
  src/lib/context-menu/index.ts
  src/lib/context-menu/public-api.ts
  src/lib/context-menu/tsconfig-build.json
  src/lib/public-api.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
  test/karma-test-shim.js
Labels: feature, new component, pr: lgtm, pr: merge ready

#74 Release v0.2.0
  README.md
  package.json
Labels: feature, pr: lgtm, pr: merge ready

#75 feat(island): island dark
  src/demo-app/island/island-demo.html
  src/demo-app/island/island-demo.scss
  src/lib/core/theming/_all-theme.scss
  src/lib/island/_island-theme.scss
Labels: design, feature, pr: lgtm, pr: merge ready
