Repository Dynatrace/ngx-groundhog, pull requests merged in 2018-03, with the labels that each got.

#84 fix(context-menu): focus and padding
  src/lib/context-menu/context-menu.html
  src/lib/context-menu/context-menu.scss
  src/lib/context-menu/context-menu.spec.ts
  src/lib/context-menu/context-menu.ts
Labels: bug, pr: lgtm, pr: merge ready

#83 feat(radio): gh-radio-button, gh-radio-group
  e2e/radio-e2e.spec.ts
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/demo-groundhog-module.ts
  src/demo-app/radio/radio-demo.html
  src/demo-app/radio/radio-demo.scss
  src/demo-app/radio/radio-demo.ts
  src/demo-app/system-config.ts
  src/e2e-app/e2e-app-module.ts
  src/e2e-app/e2e-app/e2e-app.ts
  src/e2e-app/e2e-app/routes.ts
  src/e2e-app/radio/radio-e2e.html
  src/e2e-app/radio/radio-e2e.ts
  src/e2e-app/system-config.ts
  src/lib/core/theming/_all-theme.scss
  src/lib/public-api.ts
  src/lib/radio/README.md
  src/lib/radio/_radio-theme.scss
  src/lib/radio/index.ts
  src/lib/radio/public-api.ts
  src/lib/radio/radio-module.ts
  src/lib/radio/radio.html
  src/lib/radio/radio.scss
  src/lib/radio/radio.spec.ts
  src/lib/radio/radio.ts
  src/lib/radio/tsconfig-build.json
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
Labels: feature, new component, pr: lgtm, pr: merge ready

#85 fix(tile): .gh-tile-content border radius should only be shown on bottom.
  src/lib/tile/tile.scss
Labels: bug, design, pr: lgtm, pr: needs rebase

#88 feat(progress-circle): add color
  src/demo-app/progress-circle/progress-circle-demo.html
  src/demo-app/progress-circle/progress-circle-demo.scss
  src/demo-app/progress-circle/progress-circle-demo.ts
  src/lib/progress-circle/_progress-circle-theme.scss
  src/lib/progress-circle/progress-circle.scss
  src/lib/progress-circle/progress-circle.spec.ts
  src/lib/progress-circle/progress-circle.ts
Labels: feature, pr: needs review

#90 fix(gh-icon): Don't use a slash at the begin of an url
  src/demo-app/icon/icon-demo.ts
  src/lib/icon/README.md
Labels: bug, pr: lgtm

#89 feat(theming): demo app theme switcher
  src/demo-app/demo-app/demo-app.html
  src/demo-app/demo-app/demo-app.scss
  src/demo-app/demo-app/demo-app.ts
Labels: bug, pr: lgtm

#91 feat(loading-distractor): gh-loading-distractor, gh-loading-spinner
  src/demo-app/demo-app/demo-app.scss
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/demo-groundhog-module.ts
  src/demo-app/loading-distractor/loading-distractor-demo.html
  src/demo-app/loading-distractor/loading-distractor-demo.scss
  src/demo-app/loading-distractor/loading-distractor-demo.ts
  src/demo-app/system-config.ts
  src/lib/core/style/_variables.scss
  src/lib/loading-distractor/README.md
  src/lib/loading-distractor/index.ts
  src/lib/loading-distractor/loading-distractor-module.ts
  src/lib/loading-distractor/loading-distractor.html
  src/lib/loading-distractor/loading-distractor.scss
  src/lib/loading-distractor/loading-distractor.spec.ts
  src/lib/loading-distractor/loading-distractor.ts
  src/lib/loading-distractor/loading-spinner.html
  src/lib/loading-distractor/public-api.ts
  src/lib/loading-distractor/tsconfig-build.json
  src/lib/public-api.ts
Labels: feature, new component, pr: lgtm, pr: merge ready

#23 feat(infrastructure): Add schematics for generating components
  .angular-cli.json
  package-lock.json
  package.json
Labels: feature, infrastructure, pr: lgtm, pr: needs rebase

#98 fix(tile): text truncation, fixes #95
  src/lib/tile/tile.scss
Labels: bug, pr: lgtm, pr: merge ready

#99 feat(icon): icon sizes
  src/demo-app/icon/icon-demo.html
  src/demo-app/tile/tile-demo.html
  src/lib/icon/README.md
  src/lib/icon/icon.scss
  src/lib/icon/icon.spec.ts
  src/lib/icon/icon.ts
  src/lib/select/select.scss
  src/lib/tile/tile.scss
Labels: feature, pr: needs review

#53 feat(checkbox): gh-checkbox
  README.md
  e2e/checkbox-e2e.spec.ts
  src/demo-app/checkbox/checkbox-demo.html
  src/demo-app/checkbox/checkbox-demo.scss
  src/demo-app/checkbox/checkbox-demo.ts
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/demo-groundhog-module.ts
  src/demo-app/system-config.ts
  src/e2e-app/checkbox/checkbox-e2e.html
  src/e2e-app/checkbox/checkbox-e2e.ts
  src/e2e-app/e2e-app-module.ts
  src/e2e-app/e2e-app/e2e-app.ts
  src/e2e-app/e2e-app/routes.ts
  src/e2e-app/system-config.ts
  src/lib/checkbox/README.md
  src/lib/checkbox/_checkbox-theme.scss
  src/lib/checkbox/checkbox-module.ts
  src/lib/checkbox/checkbox.html
  src/lib/checkbox/checkbox.scss
  src/lib/checkbox/checkbox.spec.ts
  src/lib/checkbox/checkbox.ts
  src/lib/checkbox/index.ts
  src/lib/checkbox/public-api.ts
  src/lib/checkbox/tsconfig-build.json
  src/lib/core/theming/_all-theme.scss
  src/lib/public-api.ts
  src/lib/radio/README.md
  src/lib/theming/theming.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
Labels: feature, new component, pr: needs review

#100 fix(form-field): fixes #97, padding on hints
  src/lib/form-field/form-field.html
Labels: bug, pr: lgtm, pr: needs rebase

#101 refactor(card): Renamed island to card
  README.md
  src/demo-app/card/card-demo.html
  src/demo-app/card/card-demo.scss
  src/demo-app/card/card-demo.ts
  src/demo-app/demo-app/demo-app.ts
  src/demo-app/demo-app/demo-module.ts
  src/demo-app/demo-app/routes.ts
  src/demo-app/demo-groundhog-module.ts
  src/demo-app/island/island-demo.html
  src/demo-app/radio/radio-demo.html
  src/demo-app/system-config.ts
  src/lib/card/README.md
  src/lib/card/_card-theme.scss
  src/lib/card/card-module.ts
  src/lib/card/card.html
  src/lib/card/card.scss
  src/lib/card/card.ts
  src/lib/card/index.ts
  src/lib/card/public-api.ts
  src/lib/card/tsconfig-build.json
  src/lib/core/theming/_all-theme.scss
  src/lib/island/README.md
  src/lib/island/island-module.ts
  src/lib/island/island.html
  src/lib/island/island.ts
  src/lib/island/public-api.ts
  src/lib/public-api.ts
  src/universal-app/kitchen-sink/kitchen-sink.html
  src/universal-app/kitchen-sink/kitchen-sink.ts
Labels: pr: lgtm
